# Generated by Django 5.1.1 on 2024-10-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
