# Generated by Django 3.2 on 2024-11-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='citation',
            name='citations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatQueryResponse',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chatconversation')),
            ],
        ),
    ]
