# Generated by Django 3.2 on 2024-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20241115_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatqueryresponse',
            old_name='text',
            new_name='query',
        ),
        migrations.AddField(
            model_name='chatqueryresponse',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
